<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20180518092935 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        // if key exists:
        $keys = $this->listTableForeignKeys('kaystrobach_contact_domain_model_contact', $schema);
        if (in_array('FK_62ADCBD85E237E06', $keys)) {
            $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_contact DROP FOREIGN KEY FK_62ADCBD85E237E06');
        }

        $keys = $this->listTableForeignKeys('kaystrobach_contact_domain_model_user', $schema);
        if (in_array('FK_A32C8B0747A46B0A', $keys)) {
            $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_user DROP FOREIGN KEY FK_A32C8B0747A46B0A');
        }

        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_contact ADD CONSTRAINT FK_62ADCBD85E237E06 FOREIGN KEY (name) REFERENCES neos_party_domain_model_personname (persistence_object_identifier)');
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_user ADD CONSTRAINT FK_A32C8B0747A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES neos_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_contact DROP FOREIGN KEY FK_62ADCBD85E237E06');
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_user DROP FOREIGN KEY FK_A32C8B0747A46B0A');
    }

    public function listTableForeignKeys($table, Schema $schema)
    {
        $conn = $this->connection->getSchemaManager();
        return array_map(
            function($key) {
                return $key->getName();
            },
            $conn->listTableForeignKeys($table)
        );
    }
}
